#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

if [ ! $(command -v gometalinter) ]
then
	go get github.com/alecthomas/gometalinter
	gometalinter --install
fi

gometalinter \
	--exclude='error return value not checked.*(Close|Log|Print)' \
	--exclude='duplicate of.*_test.go.*' \
	--tests
